# -*- coding: utf-8 -*-
#
# OSL Wiki documentation build configuration file, created by
# sphinx-quickstart on Fri Feb 14 17:25:30 2014.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys
import os
import datetime

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#sys.path.insert(0, os.path.abspath('.'))

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.graphviz',         # https://www.sphinx-doc.org/en/master/usage/extensions/graphviz.html
    'sphinx.ext.autosectionlabel', # https://www.sphinx-doc.org/en/master/usage/extensions/autosectionlabel.html
]

# True to prefix each section label with the name of the document it is in,
# followed by a colon. For example, index:Introduction for a section called
# Introduction that appears in document index.rst. Useful for avoiding
# ambiguity when the same section heading appears in different documents.
autosectionlabel_prefix_document = True

# If set, autosectionlabel chooses the sections for labeling by its depth. For
# example, when set 1 to autosectionlabel_maxdepth, labels are generated only
# for top level sections, and deeper sections are not labeled. It defaults to
# None (disabled).
autosectionlabel_maxdepth = 2

# Add any paths that contain templates here, relative to this directory. We
# have no template overrides: Furo renders the "Edit this page" link from the
# source_repository options below, and the old layout.html only injected a
# legacy Google Analytics snippet whose UA property stopped collecting data
# when Universal Analytics was shut down in July 2023.
templates_path = []

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
#source_encoding = 'utf-8-sig'

# The main toctree document.
master_doc = 'index'

# General information about the project.
project = 'OSL Wiki'
copyright = f"2014-{datetime.datetime.now().year}, Oregon State University"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = ''
# The full version, including alpha/beta/rc tags.
release = ''

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = []

# The reST default role (used for this markup: `text`) to use for all
# documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# The name of the Pygments (syntax highlighting) style to use. Left unset so
# Furo can apply its own accessible light/dark pair (a11y-light / a11y-dark);
# pinning a single style here breaks syntax highlighting in dark mode.
#pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
#keep_warnings = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'furo'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation. https://pradyunsg.me/furo/customisation/
html_theme_options = {
    # Renders the "Edit this page" link in the right-hand sidebar. This
    # replaces the old _templates/breadcrumbs.html override.
    'source_repository': 'https://github.com/osuosl/wiki/',
    'source_branch': 'master',
    'source_directory': 'source/',
    'navigation_with_keys': True,
    'light_logo': 'images/osl-logo.png',
    'dark_logo': 'images/osl-logo-dark.png',
    # OSU brand palette, matching assets/scss/_variables.scss in the
    # osuosl.org Hugo site and the osuosl/docs Sphinx site.
    #
    # Beaver Orange (#d73f09) is deliberately *not* used for links. Furo
    # applies color-brand-primary to top-level sidebar links, which are
    # normal-size text, and Beaver Orange only reaches 4.20:1 against the
    # sidebar background -- below the WCAG AA 4.5:1 floor. The darkened
    # link orange passes in both modes:
    #
    #   #c4340a on the sidebar  5.03:1
    #   #c4340a on white        5.46:1
    #   #ff7a42 on #1c1c1c      6.59:1
    #   #ff7a42 on #2a2a2a      5.55:1
    'light_css_variables': {
        'color-brand-primary': '#c4340a',      # $osu-orange-link
        'color-brand-content': '#c4340a',
        'color-brand-visited': '#c4340a',
        'color-foreground-primary': '#423e3c',  # $osu-warm-black
        'color-background-secondary': '#f7f5f5',  # $osu-neutral-100
    },
    'dark_css_variables': {
        'color-brand-primary': '#ff7a42',      # $osu-orange-link-dark
        'color-brand-content': '#ff7a42',
        'color-brand-visited': '#ff7a42',
        'color-foreground-primary': '#e9e5e4',  # $osu-neutral-200
        'color-background-primary': '#1c1c1c',  # $osu-bg-dark
        'color-background-secondary': '#2a2a2a',  # $osu-surface-dark
    },
}

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation". Furo shows this as the sidebar brand,
# where the version suffix is just noise.
html_title = 'OSL Wiki'

# A shorter title for the navigation bar.  Default is the same as html_title.
#html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
#html_logo = None

# The name of an image file to use as favicon of the docs. This is the same
# square OSL mark that osuosl.org and docs.osuosl.org serve. It lives at the
# root of _static because Sphinx copies the favicon there regardless and
# would otherwise ship it twice.
html_favicon = '_static/favicon.png'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
#html_extra_path = []

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
#html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
#html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}

# If false, no module index is generated.
#html_domain_indices = True

# If false, no index is generated.
#html_use_index = True

# If true, the index is split into individual pages for each letter.
#html_split_index = False

# If true, links to the reST sources are added to the pages.
#html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
#html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
#html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = None

# Output file base name for HTML help builder.
htmlhelp_basename = 'OSLWikidoc'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
# The paper size ('letterpaper' or 'a4paper').
#'papersize': 'letterpaper',

# The font size ('10pt', '11pt' or '12pt').
#'pointsize': '10pt',

# Additional stuff for the LaTeX preamble.
#'preamble': '',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
  ('index', 'OSLWiki.tex', 'OSL Wiki Documentation',
   'OSU Open Source Lab', 'manual'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
#latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
#latex_use_parts = False

# If true, show page references after internal links.
#latex_show_pagerefs = False

# If true, show URL addresses after external links.
#latex_show_urls = False

# Documents to append as an appendix to all manuals.
#latex_appendices = []

# If false, no module index is generated.
#latex_domain_indices = True


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    ('index', 'oslwiki', 'OSL Wiki Documentation',
     ['OSU Open Source Lab'], 1)
]

# If true, show URL addresses after external links.
#man_show_urls = False


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
  ('index', 'OSLWiki', 'OSL Wiki Documentation',
   'OSU Open Source Lab', 'OSLWiki', 'One line description of project.',
   'Miscellaneous'),
]

# Documents to append as an appendix to all manuals.
#texinfo_appendices = []

# If false, no module index is generated.
#texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
#texinfo_no_detailmenu = False
